승급전(6): 클럽 전용 모임 수정 및 삭제
1Seob/nest-study-eventory pull request #11
Opened 2024-12-01 07:23 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
1. 클럽 전용 모임 수정 API
2. 클럽 전용 모임 삭제 API

## Why
- 어떤 이유로 작업하셨나요?(Optional)
승급전 과제 수행 중입니다.

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
거의 대부분의 구현이 기존의 모임을 수정 및 삭제하는 API와 동일합니다.
어차피 호스트만 모임을 수정할 수 있고, 클럽 모임의 호스트 역시 클럽 멤버고, 또 모임을 수정할 때 clubId를 수정할 수는 없기 때문에 변경점이 없을 것이라고 생각했습니다.
다만 Response type이 clubId가 포함되어 있는 ClubEventDto여야 하기 때문에 따로 구현을 하기는 했습니다.

delete의 경우에는 99프로 동일합니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-01 08:00 UTC, worjs requested changes

2024-12-01 08:00 UTC, worjs commented on src/club/club.repository.ts
> +  }
엥 이런 기능도 있었군요 ㄷㄷ 좋은듯ㄷㄷㄷ

2024-12-01 08:00 UTC, worjs commented on src/club/club.controller.ts
> +
클럽 모임의 수정/삭제와 일반 모임의 수정/삭제의 차이점이 뭘까요?

2024-12-01 08:01 UTC, worjs commented
> 다만 Response type이 clubId가 포함되어 있는 ClubEventDto여야 하기 때문에 따로 구현을 하기는 했습니다.

이정도면 EventDto에 클럽 정보를 포함시키는 쪽으로 변경하는 방안이 더 유용하지 않을까요?
clubId?: number 정도로?

2024-12-01 15:01 UTC, 1Seob commented
역시 그 방법이 맞는 것 같습니다..
ClubEventDto는 제거했습니다!

2024-12-03 06:26 UTC, 1Seob commented
혹시 머지해도 될까요??
@worjs

2024-12-03 06:43 UTC, worjs commented
아 리퀘스트를 왠지 모르겠는데 못봤네요ㅠ
근데 이렇게 하면 기존에 Event모듈에 있는 update, delete랑 완전히 같은 로직이 되는 것 같습니다.
굳이 club event update/delete api를 별도로 개설할 이유가 있나요?

2024-12-03 07:00 UTC, 1Seob commented
> 굳이 club event update/delete api를 별도로 개설할 이유가 있나요?
만약 이것이 실제 서비스라면 클럽탭이 따로 존재해서 그쪽에서 클럽 모임을 삭제하는 기능을 지원할 것이라고 생각했습니다.

> 기존 api에서 clubId를 변경할 수 있게 하는 정도로도 충분할듯
모임을 변경할 때 clubId를 변경할 수는 없지 않나요? 기존 모임의 참가자들이 다른 클럽의 멤버가 아닐 가능성이 있고, 애초에 모임을 삭제하고 다른 클럽에서 다시 모임을 생성하는게 합리적이라고 생각합니다

2024-12-03 07:16 UTC, worjs commented
아 맞네 그쵸 clubId를 변경할 수는 없어야겠네요.
근데 그러면 더더욱 클럽 모임의 수정 api가 별도로 있을 필요가 없겠는데요?

그리고 클럽 모임 삭제도 결국은 이 모임이 클럽 모임인지 일반 모임인지 여부와 상관 없이 모임 주최자이기만 하면 삭제할 수 있으니까 별도의 api가 필요 없어보입니다.

잠깐 이야기가 돌긴 했는데, 결국 별도의 api로 구현하신 이유가

> 다만 Response type이 clubId가 포함되어 있는 ClubEventDto여야 하기 때문에 따로 구현을 하기는 했습니다.

요거였으니까, EventDto에 clubId를 포함하기로 했다면, 기존 EventDto를 사용하는 모든 api에서 clubId도 포함하여 조회하도록 수정이 필요할 것 같습니다.

2024-12-03 09:48 UTC, 1Seob commented
말씀해주신대로 클럽 모임 수정과 삭제 부분을 제거하였고,
기존 모임 조회 Api들에서 clubId도 조회하게끔 수정했습니다!

2024-12-03 13:08 UTC, worjs approved these changes

2024-12-03 13:54 UTC, merged