승급전(7): 클럽 전용 모임 참가 및 나가기 & 클럽 탈퇴
1Seob/nest-study-eventory pull request #12
Opened 2024-12-04 04:14 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
1. 기존의 모임 참가 API에 클럽에 대한 조건 추가
2. 클럽 탈퇴 API 추가

## Why
- 어떤 이유로 작업하셨나요?(Optional)
승급전 과제 진행 중입니다.

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
모임 나가기 API는 따로 만들지 않고 기존의 것을 그대로 사용하도록 했습니다.
모임 참가 API 역시 기존의 것을 사용하지만 클럽에 대한 조건을 추가했습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-04 07:34 UTC, worjs reviewed
클럽 전용 모임 참가/나가기 관련 수정은 굿!

클럽 탈퇴 관련해서만 코멘트 확인해주세요~

2024-12-04 07:34 UTC, worjs commented on src/club/club.repository.ts
> +  }
만약에 유저가 클럽에서 클럽 모임을 만들거나 참여했다면 어떻게 될까요?
단순히 ClubJoin만 지운다면, 클럽을 나온 유저인데 클럽 모임을 운영하거나 참여할 수 있게 됩니다.
그렇다고 탈퇴자와 관련된 모든 모임 참가여부와, 모임들을 삭제하는 것도 적절해 보이지는 않습니다.

이 부분을 잡아내서 어쩌라는건가요? 라고 질문하는게 출제의도(?) 였는데요,

아무튼 요거는

- 클럽에서 나올 때 기준으로 이미 끝난 클럽 모임을 운영했거나, 참여했다면 그냥 둡니다.
- 클럽에서 나올 때 기준으로 아직 시작하지 않은 모임의 호스트라면, 해당 모임을 삭제합니다.
- 클럽에서 나올 때 기준으로 아직 시작하지 않은 모임에 참가 신청 상태라면, 모임에서 나옵니다.
와 같이 구현해주시면 되겠습니다.

이미 끝난 클럽 모임이라면, 클럽을 나왔더라도 나의 참여 기록으로 아카이빙 되어서 볼 수 있어야 하기 때문이고, 아직 시작하지 않았다면 다 정리해야하는 셈이라고 보시면 됩니다!

2024-12-04 07:34 UTC, worjs commented on src/club/club.repository.ts
> +  }
추가로 모임 관련처리를 할때 역시 마찬가지로 Update, Delete와 같은 Write 쿼리를 치게 될텐데, 전부 단일 트랜잭션으로 묶어야 합니다!

2024-12-04 07:34 UTC, worjs commented on src/club/club.service.ts
> +    }
이전 코멘트와 연관해서 다시 고민해주시면 되겠습니다

2024-12-04 10:26 UTC, 1Seob commented
EventJoin을 다 날려버리면 과거의 참여를 기록으로 남길 수 없다는 걸 놓쳤었네요..
말씀해주신 케이스들을 고려하여 코드 수정 완료했습니다!

2024-12-04 14:33 UTC, worjs requested changes

2024-12-04 14:33 UTC, worjs commented on src/club/club.service.ts
> +    }
`new Date() < event.startTime`
가 반복되고 있는데, `if(new Date() > event.startTime) continue;`를 통해 미리미리 처리해버리면 더 간결하게 처리할 수 있을 것 같네요.

2024-12-04 14:33 UTC, worjs commented on src/club/club.service.ts
> +    }
반복문 안에서 쿼리 금지!

 ```
     const isUserJoinedEvent = await this.eventRepository.isUserJoinedEvent(
        event.id,
        user.id,
      );
```

2024-12-04 14:33 UTC, worjs commented on src/club/club.controller.ts
> +    @Param('clubId') clubId: number,
`ParseIntPipe`

2024-12-04 14:33 UTC, worjs commented on src/club/club.repository.ts
> +    return !!event;
이거 사용하나요?

2024-12-04 14:33 UTC, worjs commented on src/club/club.repository.ts
> +    outEvents: number[],
ID인지 Event인지 명확하게!

2024-12-04 15:27 UTC, 1Seob commented on src/club/club.service.ts
> +    }
피드백이랑 함께 다시 보니 필요 없는 부분들이 좀 있었네요..
수정하니 많이 간결해졌습니다!

2024-12-04 15:27 UTC, 1Seob commented on src/club/club.service.ts
> +    }
> 반복문 안에서 쿼리 금지!
DB 연산?이 너무 많아져서 그런 것인가요??

2024-12-04 15:28 UTC, 1Seob commented on src/club/club.controller.ts
> +    @Param('clubId') clubId: number,
앗..다른 API들에도 추가했습니다

2024-12-04 15:28 UTC, 1Seob commented on src/club/club.repository.ts
> +    return !!event;
전 구현 방식에서 썼던 거 지우는 것을 깜빡했습니다

2024-12-04 15:29 UTC, 1Seob commented on src/club/club.repository.ts
> +    outEvents: number[],
각각 ~EventsIds로 이름 변경했습니다

2024-12-04 16:01 UTC, worjs requested changes
쫌만더!!

2024-12-04 16:01 UTC, worjs commented on src/club/club.service.ts
> +      outEventsIds.push(event.id);
이렇게 하면 `user.id === event.hostId`인 경우에는 2개 배열에 모두 들어가게 되는데 그렇게 의도하신게 맞을까요!!

2024-12-04 16:01 UTC, worjs commented on src/club/club.repository.ts
> +        },
생각해보니 저번 리뷰에서 놓친건데, 얘는 eventJoin fk때문에 삭제 안될듯..? 걔도 지워주어야합니다

2024-12-04 16:21 UTC, 1Seob commented on src/club/club.service.ts
> +      outEventsIds.push(event.id);
그걸 저도 생각했었는데
delete Event 시 out Event도 이루어지기 때문에, 다시 말해 원하는 동일한 결과가 나오기 때문에 굳이 케이스를 분류하지 않았습니다

2024-12-04 16:23 UTC, 1Seob commented on src/club/club.repository.ts
> +        },
직접 실행해봤는데 문제는 없었습니다.
의도치는 않았는데 위에 outEventsIds가 deleteEventsIds의 요소를 포함하기 때문에 괜찮은 것 같습니다..?

2024-12-04 16:25 UTC, worjs commented on src/club/club.repository.ts
> +        },
음 그렇긴 한데 그건 본인의 eventjoin만 삭제하는거고, 다른 user의 eventjoin도 있을 수 있으니까 작동하지 않을거예요

2024-12-04 16:36 UTC, 1Seob commented on src/club/club.repository.ts
> +        },
아 그렇네요 모임을 삭제할 때 그 모임의 모든 eventJoin을 먼저 지워야 했죠!

2024-12-05 00:58 UTC, worjs approved these changes
고고

2024-12-05 04:20 UTC, merged