승급전(11): 클럽 삭제
1Seob/nest-study-eventory pull request #16
Opened 2024-12-06 15:57 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
 클럽 삭제 API 추가입니다

## Why
- 어떤 이유로 작업하셨나요?(Optional)
 승급전 과제입니다!

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
1. 클럽 생성, 클럽 전용 모임 생성
2. 클럽 가입 신청, 신청자 리스트 확인, 신청 승인 및 거절
3. 클럽 탈퇴
4. 클럽장 위임
5. 클럽 수정
(+ 클럽 전용 모임 수정 및 삭제를 위한 기존 로직 수정, 클럽 조회)
6. 클럽 삭제 (현재 추가할 예정인 API)

요구사항에 해당하는 API는 모두 구현한 것 같습니다. 더 추가할 기능이 있을까요??

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-06 16:08 UTC, worjs requested changes

2024-12-06 16:08 UTC, worjs commented on src/club/club.repository.ts
> +  }
음
event들을 다 지운게 아니기 때문에 club이 지워지지 않을겁니다.

2024-12-06 16:08 UTC, worjs commented on src/club/club.repository.ts
> +  }
이미 시작된 클럽 모임은 참가자를 위해 아카이브하기로 했고, 삭제할 수 없습니다.

그럼 이제 3가지의 모임 형태가 남습니다.
1. 일반 모임 -> 모두 조회 가능
2. 클럽 모임  -> 클럽원만 조회 가능
3. 아카이브된 클럽 모임 -> 참가자만 조회 가능

스키마 변경을 고려해보셔야 구현이 가능할거예요

2024-12-06 16:25 UTC, 1Seob commented on src/club/club.repository.ts
> +  }
그렇다면 Event 모델에 아카이빙 여부에 관한 필드를 추가하고, 
클럽 삭제 시에 아카이빙하는 이벤트의 아카이빙 여부를 true로 하고, clubId는 null로 하는 방식으로
구현하는 것이 괜찮을까요??

2024-12-07 02:11 UTC, worjs commented on src/club/club.repository.ts
> +  }
고고고

2024-12-07 04:16 UTC, 1Seob commented
Event 모델에 isArchived 필드를 추가하였고, 그에 따라 로직들을 수정했습니다.
또한 아카이빙된 이벤트들은 참가자 본인만 조회 가능하도록 getEvent할 때 조회에서 제외되도록 했습니다!

2024-12-07 04:28 UTC, worjs approved these changes
Club 삭제에 대해서는 Approve입니다!

다만, 코멘트에서 드린 바와 같이 조회에 대해 추가로 구현해야 할 부분이 있습니다.
새로운 PR로 주시면 감사하겠습니다ㅎㅎ,,

2024-12-07 04:28 UTC, worjs commented on src/club/club.service.ts
> +      archiveEventsIds.push(event.id);
deleteEventsTds에 들어갈게 archive에도 들어가는게 되는데,
결국 archiveEventdsIds에는 archive하지 않을 값도 들어가는 셈이니 여전히 잘못된 코드라고 생각해요.

deleteEventsIds.push(event.id); 이거 하고 바로 루프문 탈출하게 해주는게 좋을듯...

2024-12-07 04:28 UTC, worjs commented on src/event/event.repository.ts
> +        isArchived: false,
훨씬 복잡하게 보긴 하셔야 합니다.
아카이브 된 event는 참가자들은 볼 수 있어야 하니까요.

무조건 isArchived를 false로 걸면 결국 아무도 못보는 데이터가 되거든요.

아카이브된 모임에 대한 처리를 다시 한번 더 알려드릴게요.
1. 아카이브 된 모임은 참가자만 조회할 수 있습니다.
2. 아카이브 된 모임은 어차피 시작된 모임이므로, 생성, 수정, 삭제는 불가능합니다. (기존과 동일)
3. 아카이브 된 모임의 리뷰는 그 모임의 참가자들만 조회할 수 있습니다.
4. 아카이브 된 모임의 리뷰는 그 모임의 참가자들이 생성, 수정, 삭제할 수 있습니다. (기존과 동일)

1,3번을 유의해서 구현해주시면 되겠습니다.

2024-12-07 04:28 UTC, worjs commented on src/event/event.repository.ts
> +        isArchived: false,
클럽 모임도 마찬가지입니다.

클럽 모임과 그 리뷰는 클럽원들만 조회할 수 있어야 합니다.

기존에 있던 모든 조회 메소드들이 요청자에 따라 적절한 모임들을 반환하는지 체크해보세요

2024-12-07 04:34 UTC, 1Seob commented
이해했습니다. 피드백 반영하여 새로운 PR 올리겠습니다!

2024-12-07 04:34 UTC, merged