승급전(12): 기존 모임 & 리뷰 조회 로직 변경
1Seob/nest-study-eventory pull request #17
Opened 2024-12-07 08:25 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽 전용 모임, 모임의 아카이빙 추가에 따른 기존 모임, 리뷰 조회 로직 변경입니다

## Why
- 어떤 이유로 작업하셨나요?(Optional)
승급전 과제 진행 중입니다

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-07 09:10 UTC, worjs requested changes

2024-12-07 09:10 UTC, worjs commented on src/event/dto/event.dto.ts
> +
undefined나 null일 이유가 없지 않나요??!

2024-12-07 09:10 UTC, worjs commented on src/event/event.repository.ts
> +          {
쿼리 조건이 너무 복잡합니다.
OR절에서 하는 필터링은 따로 service에서 하는게 좋겠습니다.

2024-12-07 10:06 UTC, 1Seob commented on src/event/dto/event.dto.ts
> +
맞네요 수정했습니다

2024-12-07 10:07 UTC, 1Seob commented
일단 getEvents만 필터링을 service로 옮겨봤습니다. 괜찮은가요??

2024-12-08 02:12 UTC, worjs requested changes
서비스로 잘 옮겨주신듯!

2024-12-08 02:12 UTC, worjs commented on src/review/review.repository.ts
> +            ],
여기도요ㅋㅋㅋ

2024-12-08 05:18 UTC, 1Seob commented on src/review/review.repository.ts
> +            ],
리뷰 부분도 위의 로직과 유사하게 
서비스에서 필터 가능하도록 수정 완료했습니다!

2024-12-08 05:48 UTC, worjs approved these changes
오케이 가시죠

2024-12-08 06:16 UTC, 1Seob commented
넵!

1. 클럽 생성, 클럽 전용 모임 생성
2. 클럽 가입 신청, 신청자 리스트 확인, 신청 승인 및 거절
3. 클럽 탈퇴
4. 클럽장 위임
5. 클럽 조회
6. 클럽 수정
7. 클럽 삭제
(+ 클럽 전용 모임 수정 및 삭제를 위한 기존 로직 수정, 모임 및 리뷰 조회의 기존 로직 수정)

현재까지 구현한 기능들인데 여기서 더 추가해야할 것이 있을까요???

2024-12-08 06:30 UTC, worjs commented
아뇨 다 구현하신 것 같네요.
이런저런 피드백 반영하느라 고생많으셨습니다!

2024-12-08 06:57 UTC, 1Seob commented
감사합니다!!
오히려 부족한 코드들 봐주시느라 고생하셨습니다!
정말 많은 것을 배울 수 있었습니다!!!

2024-12-08 07:05 UTC, merged