Create event
1Seob/nest-study-eventory pull request #2
Opened 2024-10-30 06:46 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
모임 한 개를 조회하는 API 구현입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)
둘째주 과제에 해당합니다.

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
400, 404, 409 각 에러 처리를 제대로 했는지 여부가 궁금합니다

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-10-30 06:55 UTC, 1Seob commented
카테고리 부분은 과제1 부분인데, 싱크 포크로 동기화했을 때 git 상에서는 과제1한 부분이 날아가서 같이 뜨는 것 같습니다

2024-10-30 08:52 UTC, worjs requested changes
오 좋은데요? 조금만 고쳐서 다시 올려주시면 되겠습니다~

2024-10-30 08:52 UTC, worjs commented on src/event/event.service.ts
> +    }
엄 따로 언급은 없긴 했는데 모임 이름은 중복이 가능한걸로 하죠!

2024-10-30 08:52 UTC, worjs commented on src/event/event.service.ts
> +    const city = await this.eventRepository.getCitiesById(payload.cityId);
getCityId가 좋을 것 같네요~

2024-10-30 08:52 UTC, worjs commented on src/event/event.service.ts
> +    }
딱 한가지 시간 관련한 예외처리가 빠졌습니다~

2024-10-30 08:52 UTC, worjs commented on src/event/event.repository.ts
> +  }
호스트는 자동으로 이벤트에 참여한 것으로 한다는 요구사항이 반영되지 않았습니다!
DB 스키마를 보시면 이벤트 참여 여부를 어떻게 관리하는지 파악하실 수 있을거예요.

2024-10-30 08:52 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
요게 조금 모를만한 부분이긴 한데, 서버에 딱 전달되었을 때는 string인 상태입니다. 런타임에서도 string으로 들어오는거라서 @Type(()=>Date)를 붙여줘야 실제로 Date객체가 됩니다 ,,,,

2024-10-30 08:53 UTC, worjs commented
아 그리고 다음부터는 PR올리고 reviewer에 저를 넣어주시면 제가 메일로 받거든요! 부탁드립니다~

2024-11-06 07:40 UTC, merged

2024-11-06 07:40 UTC, 1Seob commented
넵 감사합니다!