week2: event
1Seob/nest-study-eventory pull request #2
Opened 2024-11-07 07:11 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
1. 모임을 생성하는 API
2. 모임 한 개를 조회하는 API
3. 전체 혹은 일부 모임을 조회하는 API
4. 유저가 모임에 참가하는 API
5. 유저가 모임에서 나가는 API

## Why
- 어떤 이유로 작업하셨나요?(Optional)
2주차 과제입니다

## Additional context
- 저번 레포지토리에서 1,2,3번 과제까지 완료한 PR을 제출했었는데, 당시에 리뷰해주신 것은 다음과 같았습니다.
1. 모임을 생성하는 데 있어서 시간에 관련된 예외를 하나 더 고려할 것(당시에는 시작 시간과 종료 시간을 비교하는 것에 대한 예외만 있었습니다)
2. 모임 생성 시 호스트는 자동으로 그 모임에 참가한다는 것을 반영할 것
3. @Time(() => Date) 를 사용할 것(정확한 형식인지는 모르겠습니다)

1,2번은 반영하였고 3번은 저걸 사용하니 에러가 났었는데, 다시 빼니까 잘 작동해서 일단 사용하지 않았습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.
 따라서 1,2,3번 과제는 저번 레포지토리에서 검토해주셨고, 이번 레포지토리에서 새롭게 추가된 것은 4,5번 과제입니다.
 늘 감사합니다!!

2024-11-07 11:26 UTC, worjs requested changes
전체적으로 좋습니다!
주로 변수나 함수 이름에 관련한 코멘트를 많이 달았습니다.

보통의 개발은 협업이 기본이 됩니다. 그렇다보니, 내가 쓴 코드에 대해 아무것도 모르는 개발자가 파일 이름과 클래스 이름만 보고 코드를 파악해야할 일이 많습니다. 심하면 어떤 함수를 쓰는데 함수 이름만 보고 가져다 쓸 수도 있습니다.
아무튼, 제3자가 봐도 단번에 이해할 수 있는 이름인지를 고민해보시면 이름 짓기가 수월할거예요!

2024-11-07 11:26 UTC, worjs commented on src/event/event.controller.ts
> +  }
Post 요청은 성공 시 Nestjs가 디폴트로 201을 반환합니다.
`@HttpCode(204)`요거 달아주시면 될듯!

2024-11-07 11:26 UTC, worjs commented on src/event/event.repository.ts
> +    return newEvent;
호스트도 바로 eventJoin으로 넣어주는건 좋은 접근입니다!
다만 이 경우는 newEvent에서 await을 해서 Promise가 아닌 완성된 객체를 받아오고, 아래쪽에선 그냥 newEvent.id라고 하는게 더 좋은 방법일 것 같습니다.

그런데... prisma에서는 이것보다도 더 좋은 방법이 있는데요,
https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#nested-writes
참고해주세요!

2024-11-07 11:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
사실 title이 중복되면 안된다는 조건은 어디에도 없긴합니다(?)

2024-11-07 11:26 UTC, worjs commented on src/event/event.service.ts
> +    }
JS에서 변수 이름을 동사로 시작하면 함수라고 오인하기 쉽습니다! 더 좋은 이름이 있으면 좋겠습니다~~

2024-11-07 11:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
복수의 city가 응답으로 오는 것으로 보이진 않네요!

2024-11-07 11:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
이름에 맥락이 부족해보여요. 단순히 사람 수라는 이름보다는 다른 함수들처럼 동사로 시작하는 형태의 이름이 더 좋아보입니다.

2024-11-07 11:26 UTC, worjs commented on src/event/event.service.ts
> +  }
유저 ID로 99999999999 이런거 들어오면 어떻게 될까요?

2024-11-07 11:26 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +}
두 class가 create-event.payload.ts에 있어야 할까요?
또 각각의 이름이 CreateJoinEventPayload가 적합할까요?

2024-11-07 16:42 UTC, 1Seob commented on src/event/event.controller.ts
> +  }
수정 완료했습니다!

2024-11-07 16:43 UTC, 1Seob commented on src/event/event.repository.ts
> +    return newEvent;
docs 참고하여 newEvent 생성 시 eventJoin을 동시에 생성하도록 수정하였습니다!

2024-11-07 16:44 UTC, 1Seob commented on src/event/event.repository.ts
> +  }
확인해보니 그렇네요. 이 함수는 제거하였습니다!

2024-11-07 16:44 UTC, 1Seob commented on src/event/event.service.ts
> +    }
cityID로 이름을 변경하였습니다!

2024-11-07 16:44 UTC, 1Seob commented on src/event/event.repository.ts
> +  }
함수 이름을 getCityById로 수정하였습니다!

2024-11-07 16:45 UTC, 1Seob commented on src/event/event.repository.ts
> +  }
함수 이름을 getNumberOfPeople로 수정하였습니다!

2024-11-07 16:46 UTC, 1Seob commented on src/event/event.service.ts
> +  }
너무 큰 비정상적인 유저 ID에 대하여 예외 처리를 하는 부분을 추가하였습니다!

2024-11-07 16:48 UTC, 1Seob commented on src/event/payload/create-event.payload.ts
> +}
각각의 이름에서 Create를 빼 JoinEventPayload, OutEventPayload로 이름을 수정하고, 각각을 create-event.payload.ts 안에가 아니라 개별적인 join-event.payload.ts, out-event.payload.ts에 넣었습니다!

2024-11-08 14:37 UTC, worjs requested changes
몇가지 코멘트 더 드렸습니다!

코멘트 드린 부분은 딱 해당 부분만 확인하시기 보다는, 코멘트 보시고 코드 전반적으로 비슷한 실수가 있었는지 다시 고민해보시면 좋겠습니다.

조금만 더 화이팅!

2024-11-08 14:37 UTC, worjs commented on src/event/event.service.ts
> +    }
엌 말씀드린 의도는 이게 아니었긴 해요... ㅎㅎㅎㅎㅎㅎ
다른 api들 참고해보시면 좋을듯

2024-11-08 14:37 UTC, worjs commented on src/event/event.service.ts
> +    }
변수 이름! 조회해온 데이터는 cityId가 맞나요?

2024-11-08 14:37 UTC, worjs commented on src/event/event.service.ts
> +    };
타입은 input 데이터인데 변수 이름은 event 생성하기 라는 의미를 보여주고 있어요.

2024-11-08 14:37 UTC, worjs commented on src/event/payload/join-event.payload.ts
> +    Min,
안쓰는 import는 지워주세요~~

2024-11-08 14:37 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +export class CreateEventPayload {
maxPeople에 -1같은 값을 넘겨줬을때 어떤 에러코드 내려오는지 한번 확인해보시면 좋을듯!

2024-11-08 16:44 UTC, 1Seob commented on src/event/event.service.ts
> +    }
앗 너무 단순히 생각했던 것 같습니다 ㅎㅎㅎ;;;
getUserById 활용해서 존재하지 않는 유저에 대한 예외 처리 추가했습니다

2024-11-08 16:45 UTC, 1Seob commented on src/event/event.service.ts
> +    };
createData로 변수 이름을 수정했습니다!

2024-11-08 16:46 UTC, 1Seob commented on src/event/payload/join-event.payload.ts
> +    Min,
다른 파일들에서도 안 쓰는 import들 제거 완료했습니다!

2024-11-08 16:47 UTC, 1Seob commented on src/event/payload/create-event.payload.ts
> +export class CreateEventPayload {
maxPeople에 대해 @Min(1) 추가하여 하한선을 설정했습니다!

2024-11-08 16:48 UTC, 1Seob commented on src/event/event.service.ts
> +    }
변수명을 city로 변경했습니다!

2024-11-09 07:37 UTC, worjs approved these changes
고생하셨습니다!

백엔드는 잘못된 코드가 나가면 거대한 금전적 손실로 돌아올 가능성이 있기 때문에, 책임감을 가지고 코드를 짜는게 중요해요. 엄청 별거 아닌 것 같은 것들을 계속 코멘트 드려서 조금 불편하실 수도 있는데, 이런 부분들을 하나하나 신경 쓸 정도로 꼼꼼하게 작업해보는 경험을 드리고 싶었습니다. 코멘트는 언제나 해당 부분에 대해서만이 아니라 올리신 PR 전체에 적용되는 멘트라는거 잊지 마시고요!

이번 리뷰들은 직접 수정하고 바로 머지하시면 되겠습니다!
이후 PR에서는 조금 더 고민해서 꼼꼼하게 작업해주시면 더 좋을 것 같습니다.

고생많으셨어요~~!

2024-11-09 07:37 UTC, worjs commented on src/event/event.repository.ts
> +  }
변수 없이 바로 리턴해도 될 것 같네요

2024-11-09 07:37 UTC, worjs commented on src/event/event.service.ts
> +    }
이 변수 이름도 "number" 하나로 모든 맥락이 설명이 되지는 않아보입니다.

2024-11-09 07:37 UTC, worjs commented on src/event/event.service.ts
> +    };
변수이름!

2024-11-09 07:37 UTC, worjs commented on src/event/event.service.ts
> +    };
변수이름!

2024-11-09 07:37 UTC, worjs commented on src/event/query/event.query.ts
> +import {Type} from 'class-transformer';
요기도 안쓰는 import가 보이네요

2024-11-09 07:39 UTC, worjs commented
아 그리고 충돌이 있는 것 같네요! dev rebase해서 컨플릭트 잡고 머지하시는게 좋을 것 같습니다!

2024-11-09 11:39 UTC, 1Seob commented
마지막 리뷰까지 전부 반영 완료했습니다!
그동안 협업을 한 적이 거의 없어 저만 이해할 수 있으면 되는 코드들만 짜본 지라 변수명이나 함수명을 대충 지었었는데(코파일럿을 너무 따르기도 했습니다 ㅎㅎ...), 하나하나 전부 짚어주셔서 오히려 감사했습니다! 안 좋은 습관이란 걸 다시금 깨달을 수 있었어요
앞으로는 코드 하나하나 모두 주의 깊게 신경 쓰겠습니다!! 상세하고 꼼꼼하고 친절한 리뷰 감사합니다!!!

2024-11-09 11:40 UTC, merged