week4: db migration
1Seob/nest-study-eventory pull request #4
Opened 2024-11-11 07:13 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
 Week4 과제 수행입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)
 최종 스키마로 migration하는 과정에서
 1차 migration으로 새로운 테이블(EventCity)만 추가하였고
 이를 실제로 반영하기 전에 리뷰를 받고자 PR 올렸습니다!

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-11 10:50 UTC, worjs reviewed
LGTM!

2024-11-11 15:56 UTC, 1Seob commented
기존 cityId 컬럼의 데이터를 EventCity로 이전하였고, 기존 테이블의 cityId 컬럼 제거도 완료했습니다! (2차 migration)
yarn db:save:dev 해도 될까요??

2024-11-12 15:38 UTC, worjs requested changes
넵!
마지막으로 db:save:dev 하시고, prisma client가 바뀌었을 거라 그거랑 관련한 기존 로직들 쭉 수정해주시면 됩니다. 일단 DTO가 바뀌어야 할거예요

2024-11-18 16:28 UTC, 1Seob commented
schema 변경에 따라 API랑 로직들을 변경하였고 실제로 추가, 삭제, 수정에 있어서 데이터베이스에서 적용이 잘 되는 것을 확인했습니다.
다만 문제점은, Response body에 도시들 ID 추가를 못했습니다.
EventDto에 추가하여 어떻게 해보려고 했는데, getEventById와 같은 함수에서 findUnique를 사용할 때 schema 상 event에는 cityID와 관련된 필드(?)가 없어서 여기서 막히네요...

2024-11-18 16:48 UTC, 1Seob commented
코파일럿 도움 받아서 Response body에 citiesId 리스트를 추가하긴 했으나...getEventById와 getEvents 함수가 너무 조잡해진 관계로 일단 commit하진 않았습니다;;;

2024-11-19 04:40 UTC, worjs requested changes
요거 많이 어려울 수 있어요!
고민해보고 어려우면 바로 헬프치시길

2024-11-19 04:40 UTC, worjs commented on src/event/type/create-event-data.type.ts
>    maxPeople: number;
여기를 citiesId로 하려고 해서 어려운거라고 보시면 됩니다!
결론만 말씀드리면 여기는 prisma가 리턴하는 데이터 타입을 그대로 따라하도록 타입을 만들어주시면 됩니다. eventJoin이랑 같이 select한 값의 리턴을 한번 console.log로 찍어보세요!

그리고 아래는 그에 관한 설명입니다.

> 첫시간에 각 레이어들의 역할에 대해 언급한 적이 있었는데요,
> 
> repository는 받은 정보(데이터)로 DB에 쿼리를 날리고 받아온 데이터를 리턴합니다. 해당 정보를 가지고 어떤 로직을 수행해서 다시 repository에 요청을 보내거나 이런저런 비즈니스 로직을 수행하는 곳은 Service. 최종 완성된 데이터를 받아서 응답 타입에 맞게 포맷하는 곳은 Dto 의 static 메소드에서 진행하기로 했었습니다.
> 
> 그럼 Type은 뭐냐?
> Repository는 DB에서 가져온 SQL 응답 데이터를 JS 형태로 재구성해서 타입을 만들어 줍니다. 근데 이 타입은 내가 select를 어떤 것들을 골랐냐에 따라서 바뀌도록 설계된 복잡한 타입이기 때문에 읽기가 쉽지 않습니다. 그래서 이 타입을 쉽게 주고받기 위해 우리 프로젝트에서 type이라는 계층을 도입한거라고 보시면 됩니다. repository에서 응답으로 넘겨주는 데이터를 내가 type이라는 형태로 정의해서 service에 돌려주는 것이죠. 즉, type은 repository에 더 의존하자고 정한겁니다.
> 
> 그럼 여기서 우리의 요구사항은 DTO가 바뀐다, cityIds로 내려줘야 합니다. payload도 cityIds로 받았으니 똑같이 돌려주는게 좋겠죠. 그러면 EventType과 EventDto의 형태가 다른 상황이 됩니다. 이런 상황을 핸들하려고 "포장"이라는 말을 써가며 static from 메소드를 도입하게 된 것이라고 보시면 됩니다. 지금까지는 static from 메소드에서는 말그대로 꺼내서 그대로 놓기만 해서 엄청 형식적인 곳으로 느껴졌을 수도 있는데요, data type과 dto의 차이를 메꿔주는 곳이고 여기서 형태를 응답 형태(DTO)에 맞게 새로 포장해주시면 되겠습니다.
> 
> 어찌되었건 이 방식들이 정답은 아닙니다. 제가 정한거구요, 고민해보시다가 별로라고 느껴지시면 마음대로 하셔도 됩니다. 대신 그때는 나름의 근거를 제안해주시면 좋은 토론 기회가 되겠죠!

2024-11-19 04:40 UTC, worjs commented on src/event/event.service.ts
> +        }
이렇게 해버리면 city가 1000개라면 1000번의 DB 조회를 해야 할 것이고, 왕복으로하면 2000번의 네트워크 비용이 소비되게 됩니다. 하나 요청하고 기다렸다가 다음꺼 조회 요청하고 그런 방식이니까요.

in절을 활용해보시면 좋습니다

2024-11-19 04:40 UTC, worjs commented on src/event/event.service.ts
> +        );
요거는 관련한 데코레이터가 있을거예요
payload class에서 해결해보시면 좋을듯!

2024-11-19 04:40 UTC, worjs commented on src/event/event.service.ts
> +    }
이것도 한번의 조회로 확인 가능하면 Best!

2024-11-19 04:40 UTC, worjs commented on src/event/event.repository.ts
> +    }
오 접근은 정확합니다.
다만 이 쿼리들은 Write쿼리들인데, 복수의 write쿼리를 칠땐 이 쿼리들이 일부가 도중에 실패해도 괜찮은지를 생각해봐야 합니다!

2024-11-19 04:40 UTC, worjs commented on src/event/event.repository.ts
> +    return newEvent;
여기도 마찬가지!

2024-11-19 09:58 UTC, 1Seob commented on src/event/type/create-event-data.type.ts
>    maxPeople: number;
어떤 방향인지 감은 잡히는데 "eventJoin이랑 같이 select한 값의 리턴을 한번 console.log로 찍어보세요!" 부분이 어렵네요. select를 하려면 일단 type을 정의해야 하지 않나요??

2024-11-22 07:11 UTC, 1Seob commented on src/event/type/create-event-data.type.ts
>    maxPeople: number;
어떤 느낌인지 이해는 했는데 prisma가 리턴하는 타입을 알아낼 수 있는 방법이 생각나지 않았습니다...그래서 일단 citiesId가 number 리스트인 것을 유지하고 코드를 변경하긴 했습니다

2024-11-22 07:14 UTC, 1Seob commented on src/event/event.service.ts
> +        }
유효한 도시만 추출하는 함수를 만들고 그것을 이용해 도시가 유효한지를 판별하게끔 했습니다!

2024-11-22 07:15 UTC, 1Seob commented on src/event/event.service.ts
> +        );
@ArrayNotEmpty() 추가하였습니다!

2024-11-22 07:15 UTC, 1Seob commented on src/event/event.service.ts
> +    }
여기도 위와 같은 방법으로 변경했습니다

2024-11-22 07:15 UTC, 1Seob commented on src/event/event.repository.ts
> +    }
transaction 사용하여 수정하였습니다

2024-11-22 07:16 UTC, 1Seob commented on src/event/event.repository.ts
> +    return newEvent;
여기도 transaction 사용하여 수정했습니다

2024-11-22 15:30 UTC, worjs commented on src/event/event.repository.ts
> +        })),
이것도 맞긴한데 저기 eventJoin이랑 같은 방식으로 작성해도 되지 않을까요

2024-11-22 15:30 UTC, worjs commented on src/event/event.repository.ts
> +        })),
원래를 별도의 쿼리로 치는게 맞긴한데 이왕 프리즈마가 지원하는 기능이니까?

2024-11-22 15:30 UTC, worjs commented on src/event/type/create-event-data.type.ts
>    maxPeople: number;
으흠 그렇군요 아직 TS가 익숙하지 않으셔서 그러실거예요
지금 하신거처럼 query를 바로 리턴하지 않고 변수에 담고, 거기에 마우스를 올려보면 타입이 나옵니다!
아니면 그 변수를 그대로 console.log(createdEvent)로 넣고 실행해보면 실제로 돌아오는 값을 확인할 수 있을거예요.

아래는 제가 기대한(?) 답변입니다.

-------------------------------------------------------------------------------------------------------------

data type은 repository의 반환형에 의존한다. 즉 repsitory에서 prisma가 뱉어내는 타입을 그대로 EventData 타입으로 만들주셨으면 좋겠다는 의미였습니다.

그래서 조회할 때도 eventCity들을 한번에 같이 조회하구요
```
await this.prisma.event.findMany({
      where: {
        hostId: 1,
      },
      select: {
        id: true,
        hostId: true,
        title: true,
        description: true,
        categoryId: true,
        eventCity: {
          select: {
            id: true,
            name: true,
          },
        },
        startTime: true,
        endTime: true,
        maxPeople: true,
      },
    });
```
위를 조회해서 나온 데이터의 타입은 기존과 달라지겠죠. 우린 select문을 곧바로 리턴하고 있으니까 EventData라는 타입을 바꿔줘야 타입이 맞게 됩니다. 직접 결과를 콘솔로 찍어보고 판단하셔도 되고, 응답 결과를 잠깐 변수로 받은 다음에 마우스를 올려보면 응답 타입이 나오니까 그걸 참조해도 됩니다.

그러면 EventData는 아래처럼 바뀝니다.
```
export type EventData = {
  id: string;
  hostId: string;
  title: string;
  description: string;
  categoryId: number;
  startTime: Date;
  endTime: Date;
  maxPeople: number;
  eventCity: {
     id: number;
     name: string;
  }[];
};
```

보기 안좋다 생각이 들면
event city만 따로 새로운 타입으로 할수도 있죠

```
export type CityData = {
  id: number;
  name: string;
};

export type EventData = {
  id: string;
  hostId: string;
  title: string;
  description: string;
  categoryId: number;
  startTime: Date;
  endTime: Date;
  maxPeople: number;
  eventCity: CityData[];
};
```

그럼 이제 이렇게 받아온 데이터를 static 메소드에서 포장하는겁니다.
나머지는 다 똑같을텐데 cityIds 부분만 다르죠.
`cityIds : data.eventCity.map((city) => city.id);`
이렇게 넣어주면 되겟죠?

2024-11-22 15:38 UTC, worjs requested changes

2024-11-22 15:38 UTC, worjs commented on src/event/event.service.ts
> +    /* const city = await this.eventRepository.getCityById(payload.cityId);
오... 어떻게 접근하려고 하셨는지는 매우 이해가 갑니다

2024-11-22 15:38 UTC, worjs commented on src/event/event.repository.ts
> +    const updateEvent = this.prisma.event.update({
이렇게 작성되면 cityId와 관련된 업데이트 이후 실패하면 cityId만 업데이트 되고 끝나겠는데요?
전체 update query랑 트랜잭션처리되어야 할듯!

2024-11-22 15:38 UTC, worjs commented on src/event/event.repository.ts
> +    const updateEvent = this.prisma.event.update({
https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries
참고!

2024-11-22 15:38 UTC, worjs commented on src/event/event.repository.ts
> +    return eventData;
에러가 안잡혀서... 이렇게 하신거같은데.. 이건 그냥 위에 event.update 치실 때 실수로 await 안붙여서 그렇습니다. 여유가 되시면 제가 준비해둔 자료에서 Promise, async await 관련한 부분 찾아서 공부해보시면 도움이 많이 될거예요

2024-11-22 15:38 UTC, worjs commented on src/event/event.repository.ts
> +      }),
굿!

2024-11-22 15:38 UTC, worjs commented on src/event/event.service.ts
> +    /* const city = await this.eventRepository.getCityById(payload.cityId);
다만 처음에 드린 코멘트에서 "in절"을 활용해서 쿼리를 해보면 좋다고 말씀드렸는데, 혹시 관련해서 접근해보거나 찾아보셨나요?

2024-11-23 03:25 UTC, 1Seob commented
EvenData에서 eventCity를 말씀해주신대로 변경하여 코드 전체를 대폭 수정했습니다! TS, DTO, Promise, aysnc await 등등에 대해 개념이 아직 많이 부족한 것 같아 학습을 더 해야겠습니다...
일단 위에서 언급해주신 피드백들에 대해서 전부 반영하면서 수정했습니다! 늘 감사합니다!

2024-11-23 03:27 UTC, 1Seob commented on src/event/event.service.ts
> +    /* const city = await this.eventRepository.getCityById(payload.cityId);
어떤 방식으로 하라는 건지 이해는 했었는데
for ... in 을 사용하라고 하신 줄 알고 해봤는데 안 됐어서 저런 식으로 했었는데
in 절이라는게 또 따로 있었네요
in 절을 활용하는 것으로 수정했습니다!

2024-11-23 03:28 UTC, 1Seob commented on src/event/event.repository.ts
> +    const updateEvent = this.prisma.event.update({
전체 update하는 부분을 트랜잭션 처리하는 것으로 수정 완료했습니다!

2024-11-24 04:07 UTC, worjs requested changes
코멘트 한번만 더 확인해주세요!

2024-11-24 04:07 UTC, worjs commented on src/event/event.repository.ts
> +    return eventData;
이렇게 하신 이유가 있나요? 다른 쿼리들처럼 바로 리턴하시면 될듯??
prisma에서 우리가 select한 데이터들에 맞게 타입을 바꿨으니까요

2024-11-24 04:07 UTC, worjs commented on src/event/event.repository.ts
> +
앗 그러니까 제가 말씀드린 쿼리에서의 in절은 요거였습니다.
https://lcs1245.tistory.com/entry/SQL-IN-%EA%B5%AC%EB%AC%B8

prisma도 in 조건을 지원하거든요

지금하려는게 여러개의 cityId가 DB에 존재하는지 알아보는건데, in 절로 cityID들을 넣어서 요청하면 돌아오는 row의 개수를 가지고 판단할 수 있습니다. 3,5,6으로 보냈는데 3,6만 왔으면 5는 없는 row인 셈이죠.

2024-11-24 04:07 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  eventCity!: CityData[];
음..? 왜 CityData를 input으로 받으시나요?
cityIds만 있어도 될듯?

2024-11-24 08:32 UTC, 1Seob commented on src/event/event.repository.ts
> +    return eventData;
맞네요 수정했습니다!

2024-11-24 08:34 UTC, 1Seob commented on src/event/event.repository.ts
> +
아하 prisma의 in 절을 활용하는 함수로 변경했습니다!

2024-11-24 08:36 UTC, 1Seob commented on src/event/payload/create-event.payload.ts
> +  eventCity!: CityData[];
어쩐지 작성하면서도 의아하긴 했었습니다;;
cityIds로 number 리스트만 입력받도록 수정하였습니다!

2024-11-24 09:09 UTC, worjs requested changes
코멘트 드렸습니다!
코멘트는 특정 부분에만 해당하는 건 아니라서, 코드 전체적으로 검토해주시면 감사하겠습니다~

2024-11-24 09:09 UTC, worjs commented on src/event/query/event.query.ts
> +  cityIds?: number[];
혹시 직접 테스트를 해보셨나요?
아마 이거 작동 안할거예요..ㅎㅎ

2024-11-24 09:09 UTC, worjs commented on src/event/query/event.query.ts
> +  cityIds?: number[];
그리고 여긴 검색 조건으로서의 CityId를 받는 곳인데, 복수 조건으로 받기로 변경하신건가요?

만약에 cityId를 복수로 받아서 조회하기로 하셨다면, 아래를 고려해봐야 합니다.
query는 단순한 string이어서 배열을 줄 수 가 없습니다.
/events?cityIds=3,5,6,7,8
이런식으로 "3,5,6,7,8"이라는 string으로 입력받기로 약속한 뒤, 서버에서 직접 파싱해서 배열로 만들어줘야 합니다!

2024-11-24 09:09 UTC, worjs commented on src/event/event.repository.ts
> +  }
`isCitiesIdValid`가 더 맞을듯!

2024-11-24 09:09 UTC, worjs commented on src/event/event.repository.ts
> +    return eventData;
음.. 몇 곳 더 있어보여요

2024-11-24 09:09 UTC, worjs commented on src/event/event.service.ts
> +    }
`@IsInt({ each: true })`
여기서 배열 내의 요소들에 대해 모두 Int인지 검사하라는게 each: true 옵션입니다!
null 체크 안해도 될듯

2024-11-24 09:20 UTC, 1Seob commented on src/event/query/event.query.ts
> +  cityIds?: number[];
![image](https://github.com/user-attachments/assets/fe7d0750-a71e-47bf-8a37-840f1f9eff46)
이런식으로 여러개 선택 가능하고 검색에도 문제가 없길래 되는 건지 알았습니다.
말씀해주신 방법으로 수정할까요??

2024-11-24 09:22 UTC, 1Seob commented on src/event/event.repository.ts
> +  }
사실 이 부분은 이미 push하고 발견했었는데 하나 때문에 다시 push하긴 좀 애매해서 로컬에서 수정은 했었습니다..

2024-11-24 09:23 UTC, 1Seob commented on src/event/event.service.ts
> +    }
그렇네요 null도 애초에 필터링이 되겠네요 수정했습니다!

2024-11-24 09:24 UTC, 1Seob commented on src/event/event.repository.ts
> +    return eventData;
수정했습니다!

2024-11-24 15:42 UTC, worjs commented on src/event/query/event.query.ts
> +  cityIds?: number[];
wow docs에서 이것도 지원하는줄 몰랐네요...!
그럼 괜찮을듯!

2024-11-24 15:44 UTC, worjs commented on src/event/event.repository.ts
> +    };
으음..? 코드 한번 쭉 보면서 반영 부탁드립니다ㅠㅠ

2024-11-24 15:47 UTC, worjs commented on src/event/event.service.ts
> +    } else if (payload.cityIds) {
로직을 보면 이게 else if가 아니라 그냥 if문으로 바꿔도 같거든요
else는 최대한 지양하는게 가독성에 좋습니다ㅎㅎ

다른 코드들도 한번 살펴봐주시면 좋을듯!

2024-11-24 15:47 UTC, worjs requested changes
쪼금만 더..!

2024-11-25 10:26 UTC, 1Seob commented on src/event/event.repository.ts
> +    };
앗 정말 죄송합니다 이번엔 확실히 검토했습니다..

2024-11-25 10:26 UTC, 1Seob commented on src/event/event.service.ts
> +    } else if (payload.cityIds) {
카테고리 부분에서도 else if 사용한 부분이 있었어서 그 부분도 수정했습니다!

2024-11-25 10:30 UTC, 1Seob commented
추가적으로 getEvents 할 때 도시를 복수 선택하는 경우에는 문제가 없었는데
하나만 선택했을 시 Internal server error가 떠서 무엇이 문제인가 하고 ChatGPT한테 물어보니깐
EventQuery에서 cityIds에

@Transform(({ value }) =>
    Array.isArray(value) ? value.map(Number) : [Number(value)],
  )
  
이걸 붙여줘야한다고 해서 붙여주니깐 한 개만 검색하는 것에 대해서도 잘 작동합니다!
(아마 입력이 한 개라 리스트로 인식하지 못하는 것 같습니다..?)

2024-11-25 10:41 UTC, worjs approved these changes
LGTM! 고생많으셨습니다 진짜진짜루

2024-11-25 10:41 UTC, worjs commented on src/event/query/event.query.ts
> +  )
와따 빡세네요

2024-11-25 15:40 UTC, 1Seob commented
감사합니다!!!

2024-11-25 15:40 UTC, merged