승급전(2): 클럽 생성
1Seob/nest-study-eventory pull request #7
Opened 2024-11-27 16:39 UTC by 1Seob

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
 클럽장이 클럽을 생성하는 API 추가입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)
승급전 과제 진행 중입니다.

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-28 01:47 UTC, worjs requested changes

2024-11-28 01:47 UTC, worjs commented on src/club/club.repository.ts
> +            status: 'MEMBER',
요거 Enum으로 정의하셨었죠? 
그러면 이렇게 직접 string 쓰는것보다
Enum으로 쓰는게 좋을듯

`Enum이름.MEMBER`

2024-11-28 01:47 UTC, worjs commented on src/club/club.repository.ts
> +            id: true,
clubJoin의 id값은 딱히 어디서도 필요 없을 것 같긴합니당

2024-11-28 01:47 UTC, worjs commented on src/club/dto/club.dto.ts
> +export class ClubDto {
club 사람들 list도 리턴하게 해 볼까요?

2024-11-28 01:47 UTC, worjs commented on src/club/dto/club.dto.ts
> +export class ClubDto {
userId정도면 충분할듯

2024-11-28 03:20 UTC, 1Seob commented on src/club/club.repository.ts
> +            status: 'MEMBER',
그렇게 쓸 수 있군요! 반영했습니다

2024-11-28 03:21 UTC, 1Seob commented on src/club/club.repository.ts
> +            id: true,
반영 완료했습니다!

2024-11-28 03:21 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +export class ClubDto {
ClubListDto도 추가했습니다!

2024-11-28 04:08 UTC, worjs commented on src/club/dto/club.dto.ts
> +export class ClubDto {
엄 ClubListDto가 아니라
클럽에 들어가 있는 사람들 목록도 ClubDto에 들어가게 해보자는 의미였습니다ㅎㅎ,,

2024-11-28 04:50 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +export class ClubDto {
아 맞네요 죄송합니다;;
추가했습니다!

2024-11-29 02:15 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +export class ClubDto {
아 맞네요 죄송합니다;;
추가했습니다!
@worjs

2024-11-29 02:27 UTC, worjs requested changes

2024-11-29 02:27 UTC, worjs commented on src/club/dto/club.dto.ts
> +export class ClubDto {
https://github.com/1Seob/nest-study-eventory/pull/4
요기서도 전달하려고 노력했던 부분이라ㅎㅎㅎ,, 코멘트 참고하셔서 from메소드랑 data type이랑 repository함수 등등 수정 부탁드립니다.

2024-11-29 08:40 UTC, worjs requested changes

2024-11-29 08:40 UTC, worjs commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
@ApiProperty 안에 필드 저렇게 넣어주면 swagger 사이트에서 clubJoin 타입이 제대로 보이지 않습니다.

사실 ApiProperty docs 만들어주는 @nestjs/swagger 얘 문제긴 한데, MemberData를 저기 넣으면 타입에러뜨죠?
저 자리에 Class로 된 Type을 넣어줘야해서 그렇습니다.
그래서 Dto는 항상 Class로 만들어주셔야 합니다. 얘도 새로운 Dto class를 따로 만들어주시면
type : [새로만든Dto] 이렇게 쓰실 수 있을거예요

2024-11-29 08:40 UTC, worjs commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
그리고 이름도 적절한지 조금 의문인듯! 클럽원들이라는 의미를 담은 데이터니까 더 좋은 이름으로 하면 좋겠습니다

2024-11-29 08:40 UTC, worjs commented on src/club/dto/club.dto.ts
> +      clubJoin: club.clubJoin,
객체를 직접 값으로 넣어주는거는 일단 ㄴㄴ!
다 풀어서 넣어주세요!
복잡한 이야기긴 한데, 현재 상태에서 repository로 가셔서 select할때 

```
clubJoin: {
          select: {
            userId: true,
            status: true,
            createdAt: true
          },
        },
```

이렇게 createdAt도 가져오도록 해서 실행해보세요!
분명 타입에는 userId와 status만 정의해놨는데 이게 응답까지 포함되어서 내려옵니다.
개발자의 실수로 내려가면 안되는 예민한 데이터들이 노출될 가능성이 생기기때문에, 마지막에 직접 값을 꺼내서 넣어주면서 필요한 값만 내보내는 코드라고 보시면 됩니다.

2024-11-29 13:16 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
일단 이름을 clubJoin에서 members로 변경했습니다
그리고 swagger 사이트에서 실행시
![image](https://github.com/user-attachments/assets/e19b4d32-cb4b-4453-ba1e-76014b484a5d)
이렇게 떠서 괜찮다고 생각했는데 말씀해주신대로 변경할까요??
members의 길이가 2 이상일 때도 확인해보니 괜찮게 뜨긴 했습니다

2024-11-29 13:18 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +      clubJoin: club.clubJoin,
members: club.members.map((member) => ({
        userId: member.userId,
        status: member.status,
      })),
      
이렇게 풀어서 넣는 식으로 변경하였고 예시 주신 대로 createdAt 포함해도 userId와 status만 뜨는 것도 확인했습니다

2024-11-29 13:30 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
![image](https://github.com/user-attachments/assets/df311b36-d603-4093-aad6-ba25abdf8db2)

2024-11-29 14:43 UTC, worjs commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
아하 실행했을때 나오는 결과는 문제가 없는건데, 실행해보기 전에
<img width="1520" alt="image" src="https://github.com/user-attachments/assets/4f7df474-d920-41d3-ba32-725f28bc5aa2">
요기서 잘 나와야 합니다.
프론트엔드 개발자들은 이걸 보고 response 타입을 만들거든요

2024-11-29 14:43 UTC, worjs requested changes

2024-11-29 14:43 UTC, worjs commented on src/club/dto/club.dto.ts
> +    };
굿!

2024-11-29 15:41 UTC, 1Seob commented on src/club/dto/club.dto.ts
> +  clubJoin!: MemberData[];
아하 저기서 보는 게 있었군요!
MemberDto 추가하였고 저기서 잘 나오는 것도 확인했습니다!
![image](https://github.com/user-attachments/assets/b74f3c65-cdd3-4bcb-a2bb-1876c0353db9)

2024-11-29 16:35 UTC, worjs approved these changes
고생하셨습니다!

2024-11-29 16:54 UTC, merged